/* ============================================================================
 * explanations.js — help-bubble texts, one entry per metric.
 * Filled from "Explanation File - LDE" (docx).
 *
 *   question : shown by the (?) on the question box while playing.
 *   impact   : shown by the (?) in the score Breakdown.
 *   ""       : hides that (?) button (used where the document says N/A).
 *
 * Dual-metric questions (Mandate↔Incentive slider, fuel choice) carry their
 * document text on ONE of their two metrics; the other is left "" so the
 * bubble is not duplicated.
 * ========================================================================== */

"use strict";

const EXPLANATIONS = {

  /* ------------------------------- SAF (MOD 01-03) ---------------------- */
  saf_co2_cuts: {
    question: "",
    impact: "Sustainability: Greater CO2 reductions result in SAF emitting less CO2 over its lifecycle. This in turn reduces radiative forcing, which has an overall positive impact on global temperatures.\n\nROI: A higher SAF CO2 reduction target results in SAF being harder to produce, as fewer feedstocks and fuels will be eligible. This would result in even higher costs than currently experienced due to the limited supply and difficulty to produce.\n\nTime: Depends on when the regulations would change; at the moment the next possible date to change EU SAF policy is in early 2027.",
  },
  saf_time_to_100: {
    question: "",
    impact: "Sustainability: Increasing the volume of SAF that is mandated to be supplied to EU airports would mean that more SAF is consumed by airlines, which in turn would reduce CO2 emissions and have a net positive effect on the climate.\n\nROI: SAF producers who have the ability to expand operations would benefit more, and airlines would have to pay higher costs for fuel as SAF is much more expensive than conventional jet fuel. This would most likely result in higher ticket prices, as airlines shift the costs onto the consumer.\n\nTime: ReFuelEU Aviation is set for review in early 2027, where in theory the SAF blending volume and time to 100% SAF can be changed.",
  },
  saf_WTC: {
    question: "Willingness to Contribute (WTC) measures the overall % price premium a passenger would voluntarily accept for the airline's sustainability initiative (SAF), captured via a continuous 0-100% slider. Reframed from WTP to reduce cost-salience bias, it reflects financial support as one component of broader consumer support for aviation sustainability.",
    impact: "Sustainability: Higher WTC means more passengers financially support the SAF surcharge, generating additional demand and revenue that can fund a higher SAF blend share. This has an overall positive effect on actual CO2 reductions achieved, as more contribution funds more SAF production and use.\n\nROI: Higher WTC results in greater ancillary revenue from voluntary surcharges, which helps offset the cost premium of SAF over conventional jet fuel. Low WTC means airlines must absorb more of that cost premium themselves, reducing the financial viability of scaling up SAF.\n\nTime: Unlike regulation-bound metrics, WTC is not tied to a fixed review date, but this makes it more sensitive rather than less: how the contribution is framed and communicated can shift outcomes positive or negative at any point. This makes WTC a metric that needs to be actively and carefully managed on an ongoing basis, rather than left passive.",
  },

  /* --------------------------- Bio-Sensors (MOD 04-06) ------------------ */
  biosensor_maintenance: {
    question: "Low: maintenance on the new system is harder than the current system. Medium: maintenance on the new system is the same as for the current system. High: maintenance for the new system is more efficient and less costly than for the current system.",
    impact: "Sustainability: More efficient maintenance indicates the lesser use of toxic materials and lower CO2 emissions for performing maintenance.\n\nROI: More efficient maintenance causes shorter ground time and cheaper maintenance to be executed. This will result in lower costs and more revenue for the airliner.\n\nTime: Depends on the implementation of new regulation. The current goal is 2050, but even that is optimistic.",
  },
  biosensor_reliability: {
    question: "Low: the new system is less reliable than the current system (less reliable data generated by sensors and shorter lifespan of the sensor); the system does not add value or safety and the current system will not be replaced. Medium: the new system is as reliable as the current system (same level of reliability generated by the sensor, same lifespan); no real incentive to replace the current system. High: higher reliability than the current system, clear added value with enhanced safety, and the current system will be replaced (higher reliability of data generated by the sensor, longer lifespan).",
    impact: "Sustainability: Higher reliability indicates that maintenance can be predicted better. Less maintenance will be needed and the current heavy system will be replaced. Less fuel use and toxic chemicals use, less CO2 emissions.\n\nROI: Less ground time, less use of fuel, cheaper maintenance. More revenue generated by airliners, and OEMs sell more planes.\n\nTime: Implementation now set for 2050 — an optimistic view, most likely later.",
  },
  biosensor_certification: {
    question: "Low: low certification support which obstructs the implementation of new bio-inspired and bio-based technologies. Medium: certifications focusing on a hybrid form of condition-based maintenance and non-destructive testing maintenance (an improvement from the current, but not yet fully adopted). High: certification that focuses fully on the integration of condition-based maintenance (includes predictive maintenance and structural health monitoring) and promotes the adoption of bio-inspired and bio-based sensing and communication systems.",
    impact: "Sustainability: High support of regulations increases the implementation chances of the new technologies. This supports more efficient maintenance but also the possible removal of heavy wiring and sensors. This means the aircraft becomes lighter and therefore uses less fuel and thus emits less CO2.\n\nROI: Airliners would generate more revenue, but more money needs to be invested by OEMs to show the reliability of the new technologies to regulatory bodies.\n\nTime: MSG-4 is being worked on as we speak, focusing on a hybrid form of current maintenance and condition-based maintenance. The goal of 2050 for an MSG-5 that focuses solely on condition-based maintenance should be achievable with enough research and funding. Otherwise it may take longer.",
  },

  /* --------------------- Digital Product Passport (MOD 07-09) ----------- */
  passport_digital_depth: {
    question: "The range may go from minimal identifiers like provenance, to composition data on material composition and certifications, to giving the history of everything that has been processed.",
    impact: "Sustainability: Greater data availability enables EOL (end of life) players to make more informed reuse and recycling decisions, improving material recovery outcomes.\n\nROI: For EOL players, richer information directly improves operational output and profitability; for upstream actors, it could support premium pricing, though the incentive is contested (disclosing process-level data risks competitive advantage and raises IP concerns).\n\nTime: More complete material information at EOL reduces verification overhead and accelerates processing decisions.",
  },
  passport_reg_support: {
    question: "Low: unclear guidance and no entity in charge. Medium: more guidance from regulators. High: clear guidelines and a clear body in charge.",
    impact: "Sustainability: Stronger regulatory clarity increases the likelihood of consistent, high-quality adoption, which in turn improves the material information available for EOL decision-making.\n\nROI: Clear guidance reduces compliance uncertainty and implementation costs, making the business case more predictable and lowering the risk of investing in incompatible systems.\n\nTime: Defined standards and a responsible authority eliminate the need to interpret ambiguous requirements or wait for industry consensus, accelerating deployment across the chain.",
  },
  passport_adoption: {
    question: "Low: few have it. Medium: some have it. High: everyone and every product in the aircraft supply chain is involved.",
    impact: "Sustainability: Broader adoption increases the likelihood that EOL players receive sufficient material information to make viable reuse and recycling decisions.\n\nROI: Wider adoption reduces information asymmetry more effectively across the chain, enabling all actors to operate with greater efficiency and less friction.\n\nTime: Readily available information eliminates delays caused by manual requests, document searches, or estimation, accelerating decision-making at every stage.",
  },

  /* --------------- Emission Guide & Eco-Label (MOD 19, 11, 12) ---------- */
  funding_split: {
    question: "",
    impact: "Sustainability: The allocation of funding between government, private investors, NGOs, the public, and other sources determines which decarbonisation projects can be developed and deployed.\n\nROI: Public funding helps reduce investment risk, while private funding encourages cost-efficient deployment and commercialisation.\n\nTime: Greater financial support accelerates research, certification, infrastructure development, and market uptake. Insufficient or poorly coordinated funding can significantly delay the transition.",
  },
  EGE_participation: {
    question: "",
    impact: "",
  },
  EGE_market_trust: {
    question: "",
    impact: "",
  },

  /* --------------------------- Green Transport (MOD 13-15) -------------- */
  transport_mode_shift: {
    question: "Share of cargo routed via sea/rail instead of air freight — the main lever for corridor emissions, since air freight emits roughly an order of magnitude more per unit of cargo than sea or rail.",
    impact: "Sustainability: CO₂ saved rises directly with the shift. Every percentage point moved from air to sea or rail cuts corridor emissions sharply, because air is the dominant emissions source despite carrying the smallest cargo share.\n\nROI: Improves at the same time, because sea and rail are typically cheaper per unit than air, so the shift lowers cost while cutting emissions. No trade-off is needed.\n\nTime: Fast to deliver, because this is a reallocation within existing infrastructure rather than new technology. It can be phased in quickly once urgency and packing-window constraints allow, and break-even happens almost immediately since cost drops alongside emissions.",
  },
  transport_carbon_tax: {
    question: "A price applied per tonne of CO₂e emitted.",
    impact: "Sustainability: Effectiveness depends entirely on whether the price is high enough to close the existing cost gap between the highest- and lowest-emission modes; below that threshold, pricing reinforces the existing ranking rather than changing it.\n\nROI: If low-emission modes are already cheaper, a carbon tax simply raises the highest-emitting mode's cost further without inducing a switch. So the tax becomes an absorbable surcharge rather than a decision-changing incentive.\n\nTime: Slow to deliver, because it depends on external policy setting rates high enough. This usually takes years through legislation or phased rollout, so break-even timing is uncertain and outside the company's control.",
  },
  transport_buffer: {
    question: "Days of slack between cargo readiness and required arrival, determining whether low-emission modes stay feasible or urgency forces a shift to high-emission transport.",
    impact: "Sustainability: CO₂ saved responds strongly to buffer size. A larger buffer keeps low-emission modes usable, while a smaller buffer pushes volume back onto air and raises emissions sharply.\n\nROI: Mixed rather than purely positive. Avoiding urgent air shipments lowers transport cost, but a larger buffer means releasing cargo earlier and holding more inventory in transit, which raises holding and working-capital cost. The net ROI depends on whether the transport savings outweigh the added inventory cost.\n\nTime: Fast to implement, since buffer comes from production and release scheduling rather than new technology — but the ROI payoff takes longer to materialise because it depends on that inventory cost trade-off resolving in the company's favour.",
  },

  /* ------------------------- Next-Gen Roadmapping (MOD 16-18) ----------- */
  // MOD 16 — one explanation covers the whole Mandate↔Incentive slider
  // (both nextgen_decarb_commitment and nextgen_policy_instrument).
  nextgen_decarb_commitment: {
    question: "Choose the policy instrument with the buttons (Mandate = binding, Incentive = encouraging proactive mitigation), and set the extent of the stakeholders' decarbonisation commitment with the slider (0–100).",
    impact: "Sustainability: A higher share of mandates forces more consistent and widespread adoption of decarbonisation measures, delivering greater emissions reductions. A higher share of stakeholder commitment relies more on voluntary action.\n\nROI: Mandates provide investment certainty. Stakeholder commitment allows organisations to align investments with their own business strategy, potentially improving cost-effectiveness while reducing regulatory burden.\n\nTime: Stakeholder commitments can often be implemented immediately, whereas mandates generally require potentially longer legislative and implementation processes.",
  },
  nextgen_policy_instrument: {
    question: "",
    impact: "",
  },
  // MOD 17 — one explanation covers the fuel-system choice
  // (both nextgen_tech_toggle and nextgen_tech_priority).
  nextgen_tech_toggle: {
    question: "The priority given to different technologies: SAF, hydrogen-powered aircraft, electric aircraft, and others. Set how much priority with the slider (0–100) and pick which technology with the buttons.",
    impact: "Sustainability: A higher share of hydrogen and/or electric aircraft has the potential to achieve the greatest long-term CO₂ reductions (provided low-carbon electricity and hydrogen are available). A higher share of SAF delivers immediate lifecycle emissions reductions using existing aircraft but generally offers lower long-term decarbonisation potential.\n\nROI: SAF requires limited fleet and infrastructure changes but involves high fuel costs. Hydrogen and electric aircraft require significant upfront investments in aircraft and infrastructure but may reduce operating costs over time.\n\nTime: SAF can be deployed immediately using existing fleets, whereas hydrogen and electric aircraft depend on technology maturity, certification, and infrastructure development, making large-scale deployment a longer-term transition.",
  },
  nextgen_tech_priority: {
    question: "",
    impact: "",
  },
  // MOD 18
  nextgen_actions: {
    question: "The responsibility assigned to different stakeholder groups.",
    impact: "Sustainability: A higher share of responsibility assigned to the most influential stakeholders (e.g. governments, OEMs, airlines, or others) increases the likelihood that key decarbonisation actions are implemented effectively. In addition, an unbalanced allocation might leave critical barriers unaddressed.\n\nROI: Assigning responsibilities to stakeholders best positioned to act improves investment efficiency. However, stakeholders taking on a larger share of actions may also face higher implementation costs.\n\nTime: Clearly assigning actions to the appropriate stakeholders improves coordination and accelerates implementation, whereas unclear or fragmented responsibilities can slow progress across the transition.",
  },
};
